services:
  - type: web
    name: cropdetector-backend
    env: docker
    plan: free
    region: frankfurt
    rootDir: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cropdetector-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: "2"

    healthCheckPath: "/"

databases:
  - name: cropdetector-db
    databaseName: cropdetector
    plan: free
