services:
  - type: web
    name: cropdetector-backend
    env: docker
    plan: free
    region: frankfurt

    rootDir: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    # Render will expose port 8000 automatically
    envVars:
      - key: PORT
        value: "8000"

      - key: DEBUG
        value: "False"

      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: cropdetector-db
          property: connectionString

      - key: WEB_CONCURRENCY
        value: "2"

    # Correct healthcheck for Django API
    healthCheckPath: "/api/health/"

databases:
  - name: cropdetector-db
    databaseName: cropdetector
    plan: free